/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EasyGym;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import EasyGym.UsuarioManager;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Marcus
 */
public class TelaCadastro extends javax.swing.JPanel {

    private UsuarioManager usuarioManager;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();

        usuarioManager = new UsuarioManager();
        usuarioManager.carregarUsuarios();

        ButtonGroup checkBoxGroup = new ButtonGroup();
        checkBoxGroup.add(jCheckBox1);
        checkBoxGroup.add(jCheckBox2);
        checkBoxGroup.add(jCheckBox3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNomeCompleto = new javax.swing.JTextField();
        txtDataDeNascimento = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        btnCadastrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        txtUser.setToolTipText("No mínimo 8 letras");
        txtUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User Name"));

        txtPass.setToolTipText("No mínimo 8 letras");
        txtPass.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));

        txtNomeCompleto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Completo"));

        txtDataDeNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Nascimento"));

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Aluno");

        jCheckBox2.setText("Professor");

        jCheckBox3.setText("Administrador");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        txtEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jCheckBox2)
                                        .addGap(39, 39, 39)
                                        .addComponent(jCheckBox3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addComponent(btnCadastrar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtNomeCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3))
                        .addGap(30, 30, 30)
                        .addComponent(btnCadastrar)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String username = txtUser.getText();
        String password = new String(txtPass.getPassword());
        String nomeCompleto = txtNomeCompleto.getText();
        String telefone = jTextField1.getText();
        String endereco = txtEndereco.getText();

        boolean aluno = jCheckBox1.isSelected();
        boolean professor = jCheckBox2.isSelected();
        boolean administrador = jCheckBox3.isSelected();

        if (username.isEmpty() || password.isEmpty() || nomeCompleto.isEmpty() ||
            telefone.isEmpty() || endereco.isEmpty() || (!aluno && !professor && !administrador)) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos e selecione uma opção.");
        } else if (username.length() < 8 || !isValidUsername(username)) {
            JOptionPane.showMessageDialog(this, "Nome de usuário inválido. Use apenas letras e no mínimo 8 caracteres.");
        } else if (password.length() < 8 || !isValidPassword(password)) {
            JOptionPane.showMessageDialog(this, "Senha inválida. Use apenas letras e no mínimo 8 caracteres.");
        } else {
            // Aqui você pode criar uma instância da classe Usuario e adicionar à lista de usuários
            Usuario novoUsuario = new Usuario(username, password, nomeCompleto, telefone, endereco, aluno, professor, administrador);
            usuarioManager.adicionarUsuario(novoUsuario);
            usuarioManager.salvarUsuarios();

            JOptionPane.showMessageDialog(this, "Cadastro bem-sucedido!");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private boolean isValidUsername(String username) {
        return username.matches("^[a-zA-Z]{8,}$"); // Pelo menos 8 letras
    }

    private boolean isValidPassword(String password) {
        return password.matches("^[a-zA-Z]{8,}$"); // Pelo menos 8 letras
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDataDeNascimento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
