/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import business.control.ExercicioManager;
import business.model.Exercicio;
import business.model.Usuario;
import infra.ExerciseFile;
import infra.InfraException;


import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.List;

/**
 * @author Marcus
 */
public class TelaProfessor extends javax.swing.JPanel {

    /**
     * Creates new form TelaAluno
     */

    public TelaProfessor(Usuario professor) {
        initComponents(professor.getNomeCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String nomeCompleto) {
        jPanel1 = new javax.swing.JPanel();
        btnCadastroExercicio = new javax.swing.JButton();
        btnListaExercicio = new javax.swing.JButton();
        nomeUsuario = new javax.swing.JLabel(nomeCompleto);

        btnCadastroExercicio.setText("Cadastrar exercício");
        btnCadastroExercicio.setToolTipText("");
        btnCadastroExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnCadastroExercicioActionPerformed(evt);
                } catch (InfraException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btnListaExercicio.setText("Listar exercícios");
        btnListaExercicio.setToolTipText("");
        btnListaExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnListaExercicioActionPerformed(evt);
                } catch (InfraException e) {
                    throw new RuntimeException(e);
                }
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCadastroExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnListaExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(nomeUsuario)
                                .addGap(29, 29, 29)
                                .addComponent(btnCadastroExercicio)
                                .addGap(29, 29, 29)
                                .addComponent(btnListaExercicio)
                                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup() // javax.swing.GroupLayout.Alignment.TRAILING,
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroExercicioActionPerformed(java.awt.event.ActionEvent evt) throws InfraException {
        TelaCadastroEx telaCadastroEx = new TelaCadastroEx();

        // Criar um JFrame para exibir a tela de cadastro
        JFrame frameCadastroEx = new JFrame("Cadastro de exercício");
        frameCadastroEx.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fechar apenas a janela de cadastro
        frameCadastroEx.getContentPane().add(telaCadastroEx);
        frameCadastroEx.pack();
        frameCadastroEx.setLocationRelativeTo(null); // Centralizar na tela
        frameCadastroEx.setVisible(true);
    }
    private void btnListaExercicioActionPerformed(java.awt.event.ActionEvent evt) throws InfraException {
        TelaListaEx telaListaEx = new TelaListaEx();

        ExerciseFile exerciseFile = new ExerciseFile();
        List<Exercicio> exercicios = exerciseFile.loadExercises();

        // Crie um modelo de lista a partir do ArrayList
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Exercicio item : exercicios) {
            // substituir \n
            listModel.addElement(item.getName()+"\n"+item.getDescription());
        }

        // Crie uma JList com o modelo de lista
        JList<String> lista = new JList<>(listModel);

        // Defina o modelo de seleção para SINGLE_SELECTION ou SINGLE_INTERVAL_SELECTION
        lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        lista.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Não faça nada quando o usuário tentar selecionar um item
            }
        });
        // Criar um JFrame para exibir a lista de exercícios
        JFrame frameListaEx = new JFrame("Lista de exercícios");
        frameListaEx.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fechar apenas a janela de cadastro
        frameListaEx.getContentPane().add(telaListaEx);
        frameListaEx.add(new JScrollPane(lista));
        frameListaEx.pack();
        frameListaEx.setLocationRelativeTo(null); // Centralizar na tela
        frameListaEx.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroExercicio;
    private javax.swing.JButton btnListaExercicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeUsuario;

    // End of variables declaration//GEN-END:variables
}
