/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import business.control.ExercicioManager;
import business.model.Exercicio;
import infra.InfraException;

import javax.swing.*;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.ListSelectionModel;

/**
 * @author Marcus
 */
public class TelaListaEx extends javax.swing.JPanel {

    /**
     * Creates new form TelaAluno
     */

    public TelaListaEx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        nomeUsuario = new javax.swing.JLabel();


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        )
                                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(nomeUsuario)
                                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup() // javax.swing.GroupLayout.Alignment.TRAILING,
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroExercicioActionPerformed(java.awt.event.ActionEvent evt) throws InfraException {
        TelaCadastroEx telaCadastroEx = new TelaCadastroEx();

        // Criar um JFrame para exibir a tela de cadastro
        JFrame frameCadastroEx = new JFrame("Cadastro de exercício");
        frameCadastroEx.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fechar apenas a janela de cadastro
        frameCadastroEx.getContentPane().add(telaCadastroEx);
        frameCadastroEx.pack();
        frameCadastroEx.setLocationRelativeTo(null); // Centralizar na tela
        frameCadastroEx.setVisible(true);
    }
    private void btnListaExercicioActionPerformed(java.awt.event.ActionEvent evt) {
        TelaListaEx telaListaEx = new TelaListaEx();

        // Criar um JFrame para exibir a tela de cadastro
        JFrame frameListaEx = new JFrame("Lista de exercícios");
        frameListaEx.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fechar apenas a janela de cadastro
        frameListaEx.getContentPane().add(telaListaEx);
        frameListaEx.pack();
        frameListaEx.setLocationRelativeTo(null); // Centralizar na tela
        frameListaEx.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeUsuario;
    private ExercicioManager exercicioManager;
    private List<Exercicio> exercicios;
    private javax.swing.JList<Exercicio> lista;

    // End of variables declaration//GEN-END:variables
}
